package model;

public enum Category {
    LIBROS,
    ELECTRONICA,
    ROPA_Y_ACCESORIOS,
    ALIMENTOS_Y_BEBIDAS,
    PAPELERIA,
    DEPORTES,
    BELLEZA_Y_CUIDADO_PERSONAL,
    JUGUETES_Y_JUEGOS
}
